### ISSUE TITLE
Emulator processing "empty" muons in first stage sorter

### ISSUE THREAD

**Issue by dinyar** [jlingema/uGMTScripts#38]
The emulator places muons with the empty bit set (due to pT being zero) into the set of expected intermediate muons. The firmware doesn't process these muons at all, i.e. they are set to "0 (...) 0" at the input of the deserializer already.

**Comment by jlingema** [comment]
The empty bit is just generated based on the pT when we write the patterns. I don't know if I understand fully what is needed to make them compatible with the testbench: You want the empty bits for intermediate muons to be set to 0 if they are empty, but to 1 for the out-/inputs? If so: Why does the empty bit change its meaning?

**Comment by dinyar** [comment]
No, the problem is that muons that are empty appear as intermediate muons at the output of the emulator. In the firmware they never reach intermediate muon status as all their fields are set to zero in the beginning.

**Comment by jlingema** [comment]
As mentioned before, they do not appear at the output, but anyways... The effect however then would be that for the intermediates the empty bit should be zero (i.e. "0 (...) 0" as you wrote)? Or should they not be there at all?

Anyways, it's both just one simple change in the script that writes the patterns..

**Comment by dinyar** [comment]
Yeah, but the testbench also checks the intermediates :) Yes, to be
consistent with the firmware they shouldn't appear at all in the set of
intermediate muons.

**Comment by jlingema** [comment]
OK, sorry: After looking at the pattern a bit closer it's clear what you meant. The empty muons should have no other fields != 0 in the pattern.

After thinking about it a little, I think I'll keep them in the emulator for debugging purposes (at least at the moment) but mask them to zero for the patterns.

**Comment by dinyar** [comment]
Yeah, actually sending muons with pT == 0 (and corresponding empty bit), but physical values is a useful feature I would say. The firmware should be able to deal with this (and I've already spotted a bug that may be triggered by such a situation, tracked in dinyar/uGMTfirmware#23).
